model_paths = {
    ('IDR', 'USD'): 'model/IDR-USD.h5',
    ('IDR', 'AED'): 'model/IDR-AED.h5',
    ('IDR', 'THB'): 'model/IDR-THB.h5',
    ('IDR', 'TRY'): 'model/IDR-TRY.h5',
    ('IDR', 'JPY'): 'model/IDR-JPY.h5',
    ('IDR', 'VND'): 'model/IDR-VND.h5',
    ('IDR', 'SGD'): 'model/IDR-SGD.h5',
    ('IDR', 'MYR'): 'model/IDR-MYR.h5',
    ('IDR', 'SAR'): 'model/IDR-SAR.h5',
    ('USD', 'SAR'): 'model/USD-SAR.h5',
    ('USD', 'MYR'): 'model/USD-MYR.h5',
    ('USD', 'SGD'): 'model/USD-SGD.h5',
    ('USD', 'AED'): 'model/USD-AED.h5',
    ('USD', 'THB'): 'model/USD-THB.h5',
    ('USD', 'TRY'): 'model/USD-TRY.h5',
    ('USD', 'JPY'): 'model/USD-JPY.h5',
    ('USD', 'VND'): 'model/USD-VND.h5',
    ('USD', 'IDR'): 'model/USD-IDR.h5',
    ('SAR', 'USD'): 'model/SAR-USD.h5',
    ('SAR', 'MYR'): 'model/SAR-MYR.h5',
    ('SAR', 'SGD'): 'model/SAR-SGD.h5',
    ('SAR', 'AED'): 'model/SAR-AED.h5',
    ('SAR', 'THB'): 'model/SAR-THB.h5',
    ('SAR', 'TRY'): 'model/SAR-TRY.h5',
    ('SAR', 'JPY'): 'model/SAR-JPY.h5',
    ('SAR', 'VND'): 'model/SAR-VND.h5',
    ('SAR', 'IDR'): 'model/SAR-IDR.h5',
    ('MYR', 'USD'): 'model/MYR-USD.h5',
    ('MYR', 'SAR'): 'model/MYR-SAR.h5',
    ('MYR', 'SGD'): 'model/MYR-SGD.h5',
    ('MYR', 'AED'): 'model/MYR-AED.h5',
    ('MYR', 'THB'): 'model/MYR-THB.h5',
    ('MYR', 'TRY'): 'model/MYR-TRY.h5',
    ('MYR', 'JPY'): 'model/MYR-JPY.h5',
    ('MYR', 'VND'): 'model/MYR-VND.h5',
    ('MYR', 'IDR'): 'model/MYR-IDR.h5',
    ('SGD', 'USD'): 'model/SGD-USD.h5',
    ('SGD', 'SAR'): 'model/SGD-SAR.h5',
    ('SGD', 'MYR'): 'model/SGD-MYR.h5',
    ('SGD', 'AED'): 'model/SGD-AED.h5',
    ('SGD', 'THB'): 'model/SGD-THB.h5',
    ('SGD', 'TRY'): 'model/SGD-TRY.h5',
    ('SGD', 'JPY'): 'model/SGD-JPY.h5',
    ('SGD', 'VND'): 'model/SGD-VND.h5',
    ('SGD', 'IDR'): 'model/SGD-IDR.h5'
}


csv_paths = {
    'USD': 'data/usd.csv',
    'IDR': 'data/idr.csv',
    'SAR': 'data/SAR.csv',
    'MYR': 'data/myr.csv',
    'SGD': 'data/sgd.csv'
}
