# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set the environment variable to tell Flask to run in production
ENV FLASK_ENV=production

# Expose the port that the app will run on
EXPOSE 8080

# Define the command to run the application
CMD ["python", "app.py"]
